require "user.options"
require "user.keymaps"
require "user.colorscheme"
require "user.plugins"
require "user.telescope"
require "user.gitsigns"
require "user.lualine"
require "user.nvim-tree"
require "user.bufferline"
require "user.toggleterm"
require "user.indent"
-- require "user.cmp"
-- require "user.lsp"
-- require "user.treesitter"
